# @package _global_
defaults:
- /common
- /components/model_info@model_info: xela_pretrain_jepa
- /components/data@data: socks_action_downstream_jepa
- /components/task@task: socks_action_downstream_dino
- _self_
task_name: sock_action_classification
seed: 42
ssl_model_size: tiny
ssl_name: dinov2
checkpoint_encoder: ${checkpoint}
trainer:
  devices: 1
  max_epochs: 100
  validation_frequency: 1
  sanity_validate: true
  save_checkpoint_dir: ${paths.output_dir}/checkpoints
  early_stopping_enabled: true
  early_stopping_patience: 10
  enable_progress_bar: true
data_seed: 42
experiment_name: socks/action/downstream/dino
run_name: seed${seed}
