defaults:
  - default
  - _self_

experiment_root: /workspace-SR004.nfs2/konovalov/tactile/experiments
output_dir: ${experiment_root}/significance/graph_jepa_1c4t_c50-90_t10-18

tasks:
  force:
    comparison_blocks:
      - id: graph_jepa_large_masks
        name: Graph JEPA Dijkstra (1c, 4t; context 50-90%, target 10-18%)
        baseline:
          id: original_dino
          name: Original DINO
          report_variant: only_signal
          directory: ${experiment_root}/downstream_force_dinov2/Original_*
          select: latest
        experiments:
          - id: graph_jepa_1c4t_c50_90_t10_18
            name: Graph JEPA Dijkstra (1c, 4t; c50-90%, t10-18%)
            report_variant: only_signal
            directory: ${experiment_root}/downstream_force_jepa/graph_physical_dijkstra_1c4t_c50-90_t10-18_*
            select: latest

  pose:
    comparison_blocks:
      - id: graph_jepa_large_masks
        name: Graph JEPA Dijkstra (1c, 4t; context 50-90%, target 10-18%)
        baseline:
          id: original_dino
          name: Original DINO
          report_variant: only_signal
          directory: ${experiment_root}/downstream_pose_dinov2/Original_*
          select: latest
        experiments:
          - id: graph_jepa_1c4t_c50_90_t10_18
            name: Graph JEPA Dijkstra (1c, 4t; c50-90%, t10-18%)
            report_variant: only_signal
            directory: ${experiment_root}/downstream_pose_estimation_comparison_jepa/graph_physical_dijkstra_1c4t_c50-90_t10-18_*
            select: latest

  object_classification:
    comparison_blocks:
      - id: graph_jepa_large_masks
        name: Graph JEPA Dijkstra (1c, 4t; context 50-90%, target 10-18%)
        baseline:
          id: original_dino
          name: Original DINO
          report_variant: only_signal
          directory: ${experiment_root}/downstream_object_classification_dinov2/Original_*
          select: latest
        experiments:
          - id: graph_jepa_1c4t_c50_90_t10_18
            name: Graph JEPA Dijkstra (1c, 4t; c50-90%, t10-18%)
            report_variant: only_signal
            directory: ${experiment_root}/downstream_object_classification_comparison_jepa/graph_physical_dijkstra_1c4t_c50-90_t10-18_*
            select: latest
