_target_: tactile_ssl.downstream_task.deco_policy_final.FinalDecoSparshPolicyModule
model:
  _target_: tactile_ssl.downstream_task.deco_policy_final.FinalDecoPolicyModel
  tactile_encoder:
    _target_: tactile_ssl.model.deco_${model_size}
    in_dim: 528
    in_chans: 5
    sequence_length: 3
    time_chunk_size: 3
    tokenizer_mode: direct
    num_register_tokens: 1
    pos_embed_fn: learned
    with_masktoken: false
  policy_head:
    _target_: tactile_ssl.downstream_task.deco_policy_final.FinalDecoSparshPolicyHead
    tactile_embed_dim: ${model_embed_dim}
    dim: 192
    action_dim: 12
    chunk_size: 16
    num_heads: 3
    depth: 2
    dropout: 0.1
    use_tactile: true
  train_encoder: false
  checkpoint_encoder: ${checkpoint}
  encoder_checkpoint_key: encoder
  tactile_input_mode: encoder
optim_cfg:
  _partial_: true
  _target_: torch.optim.AdamW
  lr: 0.0001
  betas:
  - 0.95
  - 0.999
  weight_decay: 1.0e-06
scheduler_cfg:
  _partial_: true
  _target_: tactile_ssl.model.custom_scheduler.WarmupCosineScheduler
  steps_per_epoch: ???
  T_max: ???
  final_lr: 1.0e-06
  start_lr: 1.0e-05
  warmup_epochs: 0
