_target_: tactile_ssl.downstream_task.xela_relativepose.XelaRelativePoseModule
checkpoint_task: null
encoder_window_batch_size: 512
model_encoder:
  _target_: tactile_ssl.model.xela_${ssl_model_size}
  in_dim: 368
  in_chans: 3
  sequence_length: 10
  time_chunk_size: 10
  num_register_tokens: 0
  pos_embed_fn: xela_2d_sincos
  with_masktoken: false
  drop_path_rate: 0.3
  drop_path_uniform: true
  normalization: null
  causal: false
  use_taxel_type_embedding: false
model_task:
  _target_: tactile_ssl.downstream_task.xela_relativepose.XelaRelativePoseDecoder
  discretize: ${data.dataset.config.discretize}
  embed_dim: ${ssl_model_size}
  num_heads: 6
  depth: 1
checkpoint_encoder: ${checkpoint}
train_encoder: false
encoder_type: ${ssl_name}
optim_cfg:
  _partial_: true
  _target_: torch.optim.Adam
  lr: 0.0001
scheduler_cfg: null
