display_name: Graph JEPA Dijkstra (1c, 4t; context 40-65%, target 5-11%)
run_name: graph_physical_dijkstra_1c4t_c40-65_t05-11
checkpoint_encoder: /workspace-SR004.nfs2/konovalov/tactile/experiments/pretrain_transformer_encoder_jepa_graph/physical_dijkstra_1c4t_c40-65_t05-11_2026.07.22_01-15/checkpoints/epoch-0500.ckpt
