display_name: JEPA (2, 4) — mix random/contiguous
run_name: jepa_mix_2c_4t
checkpoint_encoder: /workspace-SR004.nfs2/konovalov/tactile/experiments/old_jepa/pretrain_transformer_encoder_jepa/2026.07.02_20-07/checkpoints/epoch-0500.ckpt
