_target_: tactile_ssl.algorithm.SignalMAEModule
encoder:
  _target_: tactile_ssl.model.deco_${model_size}
  in_dim: 528
  in_chans: 5
  sequence_length: ${data.dataset.window_size}
  time_chunk_size: ${algorithm.encoder.sequence_length}
  tokenizer_mode: direct
  tokenizer_hidden_dim: ${model_embed_dim}
  num_register_tokens: 1
  pos_embed_fn: learned
  with_masktoken: false
  drop_path_rate: 0.3
  drop_path_uniform: true
  causal: false
mask_type: random
mask_ratio: 0.75
decoder:
  _target_: tactile_ssl.probe.reconstruction.SignalMaskDecoder
  in_dim: 528
  in_chans: 5
  sequence_length: ${algorithm.encoder.sequence_length}
  time_chunk_size: ${algorithm.encoder.time_chunk_size}
  input_embed_dim: ${model_embed_dim}
  embed_dim: 192
  depth: 4
  num_heads: 12
  pos_embed_fn: sinusoidal
  mlp_ratio: 4.0
  qkv_bias: true
optim_cfg:
  _partial_: true
  _target_: torch.optim.AdamW
  lr: 1.0e-4
  weight_decay: 0.05
lr_scheduler_cfg:
  _partial_: true
  _target_: tactile_ssl.model.custom_scheduler.WarmupCosineScheduler
  steps_per_epoch: ???
  T_max: ???
  final_lr: 1.0e-6
  start_lr: 1.0e-5
  warmup_epochs: 5
wd_scheduler_cfg:
  _partial_: true
  _target_: tactile_ssl.model.custom_scheduler.CosineWDSchedule
  final_weight_decay: 0.4
  ref_weight_decay: 0.04
  T_max: ???
online_probes: []
online_probes_lrs: []
