_target_: tactile_ssl.algorithm.TactileBYOLModule
encoder:
  _target_: tactile_ssl.model.TemporalTactileAlexNet
  rasterizer:
    _target_: tactile_ssl.model.DecoTactileRasterizer
  sequence_length: ${data.dataset.window_size}
  time_chunk_size: ${algorithm.encoder.sequence_length}
  embedding_dim: ${model_embed_dim}
  pretrained: true
  image_size: 224
augment_fn:
  _target_: tactile_ssl.algorithm.TactileBYOLAugment
  image_size: 224
  crop_scale: [0.9, 1.0]
  crop_probability: 0.5
  blur_probability: 0.5
  blur_kernel_size: 3
  blur_sigma: [1.0, 2.0]
projection_dim: 256
projection_hidden_dim: 4096
moving_average_decay: [0.994, 1.0]
optim_cfg:
  _partial_: true
  _target_: torch.optim.AdamW
  lr: 1.0e-4
  weight_decay: 0.05
lr_scheduler_cfg:
  _partial_: true
  _target_: tactile_ssl.model.custom_scheduler.WarmupCosineScheduler
  steps_per_epoch: ???
  T_max: ???
  final_lr: 1.0e-6
  start_lr: 1.0e-5
  warmup_epochs: 5
wd_scheduler_cfg:
  _partial_: true
  _target_: tactile_ssl.model.custom_scheduler.CosineWDSchedule
  final_weight_decay: 0.4
  ref_weight_decay: 0.04
  T_max: ???
