_target_: tactile_ssl.downstream_task.sock.SockPoseCNNModule
checkpoint_task: null
model_encoder:
  _target_: tactile_ssl.downstream_task.sock.SockBaselineIdentity
model_task:
  _target_: tactile_ssl.downstream_task.sock.SockPoseCNN
  window_size: 60
  n_outputs: 69
checkpoint_encoder: null
train_encoder: false
encoder_type: baseline
optim_cfg:
  _partial_: true
  _target_: torch.optim.Adam
  lr: 0.001
  weight_decay: 0.0001
scheduler_cfg: null
