#@package _global_

task_name: downstream_object_classification_comparison
ssl_model_size: tiny
experiment_name: ${task_name}_${ssl_name}
seed: 42

run_name: jepa_${now:%Y.%m.%d}_${now:%H-%M}

hydra:
  job:
    id: ${now:%Y.%m.%d}_${now:%H-%M}
  run:
    dir: ${paths.log_dir}/${experiment_name}/${run_name}_${hydra.job.id}

trainer:
  # Reference Xela downstream runs use one GPU.
  devices: 1
  max_epochs: 100
  validation_frequency: 1 
  sanity_validate: true
  save_checkpoint_dir: ${paths.output_dir}/checkpoints
  checkpoint_interval_type: "log"
  max_task_checkpoints: 10
  save_probe_weights_only: True

  early_stopping_enabled: true
  early_stopping_patience: 10
  early_stopping_delta: 0.00001


task:
  _target_: tactile_ssl.downstream_task.XelaObjectSLModule
  checkpoint_task: ~

  # model_encoder:
  #   _target_: tactile_ssl.model.xela_${ssl_model_size}
  #   in_dim: 368
  #   in_chans: 3 # 6
  #   sequence_length: 10
  #   time_chunk_size: 10
  #   pos_embed_fn: learned
  #   num_register_tokens: 1
  #   with_masktoken: True
  #   drop_path_rate: 0.3
  #   drop_path_uniform: True
  #   causal: False
  #   normalization:

  # JEPA
  model_encoder:
    _target_: tactile_ssl.model.xela_${ssl_model_size}
    in_dim: 368 
    in_chans: 3 
    sequence_length: 10
    time_chunk_size: 10
    num_register_tokens: 0
    pos_embed_fn: learned
    with_masktoken: False
    drop_path_rate: 0.3
    drop_path_uniform: True
    normalization: 
    causal: False

  model_task:
    _target_: tactile_ssl.probe.classification.LinearClassifier
    input_embed_dim: ${model_info.${ssl_model_size}.embed_dim}
    classes: ${data.object_classes}
    class_weights: ${data.object_class_weights}

  checkpoint_encoder: ${checkpoint_encoder}
  train_encoder: false
  encoder_type: ${ssl_name}

  optim_cfg:
    _partial_: True
    _target_: torch.optim.AdamW
    lr: 1e-4
    weight_decay: 0.05

  scheduler_cfg: ~
