#@package _global_

task_name: downstream_pose_estimation_comparison
ssl_model_size: tiny
experiment_name: ${task_name}_${ssl_name}
seed: 42

hydra:
  job:
    id: ${now:%Y.%m.%d}_${now:%H-%M}
  run:
    dir: ${paths.log_dir}/${experiment_name}/${hydra.job.id}

run_name:  transformer_${now:%Y.%m.%d}_${now:%H-%M}

trainer:
  # Reference Xela downstream runs use one GPU.
  devices: 1
  max_epochs: 25
  validation_frequency: 1
  sanity_validate: true
  save_checkpoint_dir: ${paths.output_dir}/checkpoints
  checkpoint_interval_type: "log"
  max_task_checkpoints: 10
  save_probe_weights_only: True

  early_stopping_enabled: true
  early_stopping_patience: 10
  early_stopping_delta: 0.00001


data:
  dataset:
    config:
      train_data_budget: ${train_data_budget}
      val_data_budget: ${val_data_budget}

# test:
#   data:
#     dataset_name: [
#       # "val/pringle_can/20241105_14",
#       # "val/pringle_can/20241105_15",
#       # "val/pringle_can/20241105_16",
#       # "val/pringle_can/3",
#       # "val/pringle_can/4",
#       # "val/pringle_can/bag40",
#       # "val/pringle_can/bag41",
#       "val/pringle_can/bag42",
#       "val/pringle_can/bag43",
#       "val/pringle_can/bag46",
#       # "val/pringle_can/bag48",
#       # "val/pringle_can/bag49",
#     ]
#     batch_size: ${data.val_dataloader.batch_size}
#     dataset:
#       _target_: tactile_ssl.data.xela_pose_estimation.RelativePoseDataset.get_single_sequence
#       data_path: ${data.dataset.data_path}
#       urdf_path: ${data.dataset.urdf_path}
#       baseline_signal_path: ${data.dataset.baseline_signal_path}
#       config: ${data.dataset.config}
#   tester:
#     _partial_: True
#     _target_: tactile_ssl.test.TestXelaRelativePoseEstimation
#   path_outputs: ${paths.tacbench_dir}/${task_name}_${sensor}/

task:
  _target_: tactile_ssl.downstream_task.xela_relativepose.XelaRelativePoseModule
  checkpoint_task: ~

  # model_encoder:
  #   _target_: tactile_ssl.model.xela_${ssl_model_size}
  #   in_dim: 368
  #   in_chans: 3 # 6
  #   sequence_length: 10
  #   time_chunk_size: 10
  #   pos_embed_fn: learned
  #   num_register_tokens: 1
  #   with_masktoken: True
  #   drop_path_rate: 0.3
  #   drop_path_uniform: True
  #   causal: False
  #   normalization:

  # model_encoder:
  #   _target_: tactile_ssl.model.XelaLinear
  #   in_dim: 368 # total number of xela sensors in hand
  #   in_chans: 3 # 6 # 3 xela mag channels + 3 position channels
  #   sequence_length: 10
  #   time_chunk_size: 10
  #   pos_embed_fn: learned
  #   num_register_tokens: 1
  #   with_masktoken: True
  #   normalization: ${data.normalization}

  model_encoder:
    _target_: tactile_ssl.model.xela_${ssl_model_size}
    in_dim: 368 
    in_chans: 3 
    sequence_length: 10
    time_chunk_size: 10
    num_register_tokens: 0
    pos_embed_fn: learned
    with_masktoken: False
    drop_path_rate: 0.3
    drop_path_uniform: True
    normalization: 
    causal: False

  model_task:
    _target_: tactile_ssl.downstream_task.xela_relativepose.XelaRelativePoseDecoder
    discretize: ${data.dataset.config.discretize}
    embed_dim: ${ssl_model_size}
    num_heads: 6
    depth: 1

  checkpoint_encoder: ${checkpoint_encoder}
  train_encoder: false
  encoder_type: ${ssl_name}

  optim_cfg:
    _partial_: True
    _target_: torch.optim.Adam
    lr: 0.0001

  scheduler_cfg: ~
