data_root: /workspace-SR004.nfs2/kovtun/tactile/sparsh-skin-dataset
log_dir: /workspace-SR004.nfs2/kovtun/tactile/experiments/
tensorboard_dir: /workspace-SR004.nfs2/kovtun/tactile/lightning_logs/
encoder_checkpoint_root: /workspace-SR004.nfs2/kovtun/tactile/hf_checkpoints/sparsh-skin/

output_dir: ${hydra:runtime.output_dir}
work_dir: ${hydra:runtime.cwd}
