# @package _global_
defaults:
- /common
- /components/model_info@model_info: xela_pretrain_jepa
- /components/data@data: socks_action_pretrain_jepa
- /components/algorithm@algorithm: socks_action_pretrain_jepa
- _self_
seed: 42
model_size: tiny
model_embed_dim: ${model_info.${model_size}.embed_dim}
trainer:
  max_epochs: 500
  grad_clip_norm: 10.0
  validation_frequency: 5
  checkpoint_frequency: 50
  log_frequency: 1
  save_checkpoint_dir: ${paths.output_dir}/checkpoints
  max_steps: null
  devices: 4
  enable_progress_bar: true
task_name: pretrain_sock_encoder
ssl_name: jepa_graph
experiment_name: socks/action/pretrain/jepa
run_name: seed${seed}
pretrain_seed: ${seed}
